### PR TITLE
Overview and logged out state styling

### PR DESCRIPTION
**Pull request by Arcslogger**
also mightve ran prettier on a buncha things?

---
### screenshots
image

### CODE REVIEW

**Review by Ynng — APPROVED** [review]
lgtm!

**Review by NicholasLin718 — COMMENTED** [review]
Try rolling back your package-lock.json so there aren't 31k line changes :)

**Review by NicholasLin718 — CHANGES_REQUESTED** [review]
Roll back to either lock file 1 to match current or lock file 3 to match 0.4.2

**Review by NicholasLin718 — APPROVED** [review]
lgtm 🥇 🚢

**Review by Ynng — CHANGES_REQUESTED** [review]
It might be nice to apply the same UI changes to the home page
image

**Comment by Ynng** [comment]
Also the spacing/design is a little weird,
as in, the performance graphs are a darker color with no border,
but playerlist is a lighter color with border

the vertical spacing is also a little confusing, it might be nice to decrease the space between the "section subtitle"(All players that are currently online) and the "content" (Name), same for the graphs
image

**Pull request merged**
