### PR TITLE
unzip into the current directory

### LINKED ISSUE #227: Frontend should not try to resolve duplicate file name when unzipping
Backend already does it automatically, and it seems like `getNonDuplicateFolderNameFromFileName` is faulty as it always produce somefilename-1 when unzipping, even when there isn't a duplcate

https://github.com/Lodestone-Team/lodestone/blob/b060ce9e6cb2cd7599bf662d0ef358dc432615ed/src/components/FileViewer/FileViewer.tsx#L207-L228

### PR DESCRIPTION
**Pull request by CheatCod**
closes #227

### CODE REVIEW

**Review by Ynng — COMMENTED** [review]
Wouldn't this cause the contents of the zip file to "spill out" into the current directory?

**Comment by Ynng** [comment]
Also did you meant to pull request into 0.5.0 not main

**Comment by CheatCod** [comment]
> Wouldn't this cause the contents of the zip file to "spill out" into the current directory?

I think you are used to the "Smart unzip" option in bandzip that minimize spillage, but this should be the intended behavior of unzip,

**Comment by CheatCod** [comment]
> Also did you meant to pull request into 0.5.0 not main

no i will be making a minor release to fix this stupid unzip bug

**Comment by Ynng** [comment]
> > Wouldn't this cause the contents of the zip file to "spill out" into the current directory?
> 
> I think you are used to the "Smart unzip" option in bandzip that minimize spillage, but this should be the intended behavior of unzip, 

Well even when using 7zip, I always use the "unzip xxx.zip to ./xxx" option instead of "unzip xxx zip"
Do we even have an "unzip to another folder" feature?

**Comment by CheatCod** [comment]
No as that will require new UIs which don't exsit

**Review by Ynng — APPROVED** [review]
I couldn't test it but looks like it'll work.
If it works for you then it's probably good.

**Comment by CheatCod** [comment]
image
we can do something like this? To provide an option to unzip to a folder

**Comment by Ynng** [comment]
> image
> we can do something like this? To provide an option to unzip to a folder

Yeah we can do that in the future.
Also just curious, how do we currently handle duplicate files during unzip?

**Comment by CheatCod** [comment]
Yes by default it will not override anything

**Comment by Ynng** [comment]
Alright let's merge this then.

**Pull request merged**
